sudo: false

os:
  - linux

services:
  - docker

compiler:
  - gcc
  - clang

language:
  - c

before_install:
  - docker pull ebassi/mutestci:latest

before_script:
  - echo FROM ebassi/mutestci > Dockerfile
  - echo ADD . /home/user/app >> Dockerfile
  - echo WORKDIR /home/user/app >> Dockerfile
  - docker build -t withgit .

script:
  - docker run withgit /bin/sh -c "CC=$CC sh -x .travis-ci/run-tests.sh"
