name: Alpine GCC Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
    - uses: actions/checkout@v2
    - name: set up environment
      run: |
        apk add gcc musl-dev py3-wheel py3-setuptools ninja py3-pip
        pip install meson==1.0.0

    - name: default build
      run: |
        meson setup --werror --fatal-meson-warnings _build_default
        meson compile -C _build_default
        meson test -C _build_default -v
